<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="LAPTOP-VLAJ5DTN" failures="1" tests="3" name="Surefire test" time="12.473" errors="0" timestamp="15 Jun 2020 14:49:47 GMT">
  <testcase classname="DAL.ClientDAOTest" name="Insert_cas1 on Insert_cas1(DAL.ClientDAOTest)" time="4.254">
    <failure type="java.lang.AssertionError" message="Error in test insert_cas1 Communications link failure

The last packet sent successfully to the server was 0 milliseconds ago. The driver has not received any packets from the server.">
      <![CDATA[java.lang.AssertionError: Error in test insert_cas1 Communications link failure

The last packet sent successfully to the server was 0 milliseconds ago. The driver has not received any packets from the server.
	at org.junit.Assert.fail(Assert.java:93)
	at DAL.ClientDAOTest.Insert_cas1(ClientDAOTest.java:74)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:45)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:15)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:42)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:20)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:263)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:68)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:47)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:231)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:60)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:229)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:50)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:222)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:300)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:157)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:136)
... Removed 27 stack frames]]>
    </failure>
  </testcase> <!-- Insert_cas1 on Insert_cas1(DAL.ClientDAOTest) -->
  <testcase classname="DAL.ClientDAOTest" name="Insert_cas3 on Insert_cas3(DAL.ClientDAOTest)" time="4.078"/>
  <testcase classname="DAL.ClientDAOTest" name="Insert_cas2 on Insert_cas2(DAL.ClientDAOTest)" time="4.087"/>
</testsuite> <!-- Surefire test -->
